### ISSUE TITLE
Kontronik Pinout coreect?

### ISSUE THREAD

**Issue by garfield2412** [eyal113/kontronik-bluetooth#1]
Hi there,

I tried to make one of These awesome Modules.
Solderes as described.
Are you sure the shown Pinout is right?
If i Connect the Board for testing to 5v and GND (two outer Pins), the LED will Go Red.
If i connect the Module to Kosmik or Jive Pro, nothing happens.
Measured the two outer Pins from JivePro and Kosmik, No Voltage is measured.

**Comment by eyal113** [comment]
Hi ,
I'm sure that's the right pinout for the jst-5 pin connector.
I've created more than 10 modules and all seems good.
Did you tried to measured the voltage while the ESC was connected to a valid reciever signal and connected to a motor ?

**Comment by garfield2412** [comment]
Hi,I measured the Voltage with Connection to valid Signal (but without Motor).Maybee thats wrong.KaYGesendet von Outlook für Android

**Comment by garfield2412** [comment]
Valid Signal, Motor Connected, Initializing Beeps from Jive Pro 120+, but only 0,06V on the outer Pins.
No Red light on the WiFi Board.

Im going Mad... whats wrong with my Setup :-(
![IMG_20230927_235945](https://github.com/eyal113/kontronik-bluetooth/assets/33608374/1d09a190-ffd5-4f78-b041-fa37944aa0b7)

**Comment by eyal113** [comment]
Your wiring looks good ...i'm not seeing any mistake.
Are you sure that all the pins are in place ? maybe when you plugged in the connector one of them bended ?

Here's my setup, you can see that the fluke is reading ~5v when measuring the outer two pins![fluke](https://github.com/eyal113/kontronik-bluetooth/assets/24767399/75dc1386-416d-484c-a7f9-67c3a0f34adf)

![connector](https://github.com/eyal113/kontronik-bluetooth/assets/24767399/ff5921b7-4e7b-46f2-92f0-c591c986427d)

**Comment by garfield2412** [comment]
Your Picture now Shows a 180° different wiring than the Picture in the Wiki!
If you can See the Pins, from Top, you See left is Black and Right ist Red.
Then the small notch on the Connection ist near to the Bottom.
If you Look at you Kosmik Picture, the notch is also in the facing the Bottom, but there you that left ist 5v and Right ist GND ?
Also the RX/TX Pins are different to the actual shown Connector wiring.

Nevertheless... i can't measure 5v on the outer Pins (on my JivePro)

If i Look to my Kosmik, there ist currently a Fan attached to the First Connector. The third Connector is free. I'll try If ony Port 1 has 5v for BT in the Kosmik

**Comment by garfield2412** [comment]
Ok, now i can See a Red light on the Module! But only when Connected to Kosmik! Jive Pro seems to have No 5v???

Can't See the Module via Smartphone Bluetooth also...

**Comment by eyal113** [comment]
You're right ! I'll fix the pinout image.
Regarding the jive pro, I could measure 5v same as the Kosmik. So I can't tell what's wrong in your unit.

**Comment by garfield2412** [comment]
Okay, Works on my Kosmik 200.
My JivePro 120+ has No 5V...
Will ASK the K-Guy's not a fault of the awesome Project Here!

Thank you!
